Dev
Vuklorr/Prog pull request #1
Opened 2022-03-02 20:03 UTC by Vuklorr

Создал интерфейс в hpp, но без Rule of Five.

2022-03-03 10:09 UTC, DmitriySud requested changes

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +#ifndef BIG_INTEGER_HPP
Это необязательные макросы (да, я знаю, что их автоматом создаёт clion ) можно заменить на ´#pragma once´. Функция та же самая, не давать хэдэру подключаться дважды

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.cpp
> +BigInteger::BigInteger(std::string &str) {
Если посмотришь документ, что я скидывал,  то увидишь, что мы должны хранить числа «задом наперёд», то есть младшие разряду лежат по меньшему индексу. Связано с тем, что когда число будет увеличиваться, нам будет легче его расширить , добавив в конец новый разряд, а если старший разряд в 0-ом индексе, то придётся двигать весь массив, чтобы вставить в начало

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.cpp
> +#include "big_integer.hpp"
Давай всё-таки делать ПР на задачу. Если хочешь поделать часть из следующей задачи, сделай новую ветку из ветки dev, и тогда в ней будут все изменения, что и в dev, а когда мы вмёржим dev, продолжишь в новой

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    std::vector<int> num;
Лучше явно прописать модификатор доступа ( да, тут он по умолчанию private, но если ты это напишешь явно, то будет проще понять)

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger(int& val);
Если внутри не будете менять объект, то надо его сделать константным

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger(std::string& str);
- std::string - > std::string_view (заодно узнаешь что это и зачем) 
- const

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator%(BigInteger& val);
Все операторы - константные метод, и принимают константные параметры

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator-();
- const операторы
- const параметры

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator%=(BigInteger& val);
- Операторы присваивания возвращают значение по референсу
- const параметры

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    bool operator >=(BigInteger& val);
- эти операторы могут быть константрыми
- принимаемые параметры константные

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    int operator%(int& val);
- Big Integer в сумме с int не может дать int (остальные операции тоже) 
- const оператор
- const параметры

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    bool operator ==(int& val);
- const операторы
- const параметры

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    bool operator >=(int& val);
- Операторы сравнения с int давай все же в одной группе хранить (перенеси выше к остальным)
- const операторы
- const параметры

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    int operator%=(int& val);
- те же комменты, что и к другим операциям с интом
- те же комменты, что и к другим оператором присваивания

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    void ToString();
- Константный метод
- это же преобразование к строке, так что должна возвращаться строка

2022-03-03 10:09 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    friend std::ostream operator<<(std::ostream& out, const BigInteger& val);//??????????friend???
friend методы - внешние методы, которые имеют доступ к приввтным членам  класса. Также friend могут быть классы


То есть грубо говоря этот метод должен существовать вне класса, а внутри класса должен быть только объявлен

Посмотри где-нибудь примеры, их должно быть много

Так же, когда выводим, можно передать выводимое значение по константной ссылке

2022-03-03 14:17 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +#ifndef BIG_INTEGER_HPP
+

2022-03-03 14:20 UTC, Vuklorr commented on works/big-integer/src/big_integer.cpp
> +BigInteger::BigInteger(std::string &str) {
+

2022-03-03 14:24 UTC, Vuklorr commented on works/big-integer/src/big_integer.cpp
> +BigInteger::BigInteger(std::string &str) {
123

2022-03-03 14:25 UTC, Vuklorr commented on works/big-integer/src/big_integer.cpp
> +BigInteger::BigInteger(std::string &str) {
123

2022-03-03 14:25 UTC, Vuklorr commented on works/big-integer/src/big_integer.cpp
> +BigInteger::BigInteger(std::string &str) {
123

2022-03-03 14:30 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +#ifndef BIG_INTEGER_HPP
123

2022-03-03 14:33 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    std::vector<int> num;
+

2022-03-03 14:34 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    BigInteger(int& val);
+

2022-03-03 14:37 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    bool operator ==(int& val);
+

2022-03-03 14:44 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    bool operator >=(int& val);
+

2022-03-03 14:45 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    int operator%=(int& val);
+

2022-03-03 14:46 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    void ToString();
+

2022-03-03 17:18 UTC, Vuklorr commented on works/big-integer/src/big_integer.cpp
> +#include "big_integer.hpp"
+

2022-03-03 17:18 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    friend std::ostream operator<<(std::ostream& out, const BigInteger& val);//??????????friend???
+

2022-03-03 18:05 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    const BigInteger operator+(const BigInteger& val);
константные операторы - это не те, которые возвращают `const`
https://ru.stackoverflow.com/questions/9318/Константные-методы

2022-03-03 18:05 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    friend std::ostream operator<<(std::ostream& out, const BigInteger& val);//??????????friend???
Объявления вне класса так и нет, так что не "+"

2022-03-03 18:37 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    const BigInteger operator+(const BigInteger& val);
+

2022-03-04 13:47 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    friend std::ostream operator<<(std::ostream& out, const BigInteger& val);//??????????friend???
исправил, но не реализовал оператор ввода

2022-03-04 15:11 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator%=(BigInteger& val);
Still not fixed

2022-03-04 15:11 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger(std::string& str);
Still not fixed

2022-03-04 15:13 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    bool operator <=(const BigInteger& val) const;
Давай все операторы сравнения положим вместе

2022-03-04 15:13 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    int operator%(int& val);
Пункт 1 still not fixed

2022-03-04 15:16 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator%=(BigInteger& val);
Операторы присваивания не должны быть константным, они же присваивают новое значение…

2022-03-04 15:16 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    int operator%=(int& val);
Не пофикшено 
Возвращаемое значение неверное, константность неверна

2022-03-04 15:17 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    void ToString();
Пункт 1 not fixed yet

2022-03-04 15:22 UTC, DmitriySud requested changes

2022-03-04 15:22 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger toInt(BigInteger& val) {//добавил для >>
В рамках данного ПР-а не должно быть реализации, только объявление

2022-03-04 15:22 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +std::ostream& operator<<(std::ostream& out, const BigInteger& val) {
Без реализации, только объявление

2022-03-04 15:22 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +std::istream& operator>>(std::istream& in, BigInteger& val) {//криво - косо, с костылями, но работает
Без реализации, только объявление

2022-03-04 17:39 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    bool operator <=(const BigInteger& val) const;
+

2022-03-04 17:39 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    BigInteger toInt(BigInteger& val) {//добавил для >>
+

2022-03-04 17:39 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +std::ostream& operator<<(std::ostream& out, const BigInteger& val) {
+

2022-03-04 17:41 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    int operator%=(int& val);
+

2022-03-04 17:42 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    void ToString();
+

2022-03-04 17:42 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +std::istream& operator>>(std::istream& in, BigInteger& val) {//криво - косо, с костылями, но работает
+

2022-03-04 22:35 UTC, DmitriySud requested changes

2022-03-04 22:35 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator%(const int& val) const;
Если брать модуль по инту, то возвращаемое значение наверное инт тоже будет

2022-03-04 22:35 UTC, DmitriySud commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator%=(const int& val);
Возвращаемое значение наверное инт

2022-03-06 08:44 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator%(const int& val) const;
+

2022-03-06 08:44 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator%=(const int& val);
+

2022-03-06 12:23 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    BigInteger(std::string& str);
+

2022-03-06 12:24 UTC, Vuklorr commented on works/big-integer/src/big_integer.hpp
> +    BigInteger operator%=(BigInteger& val);
+

2022-03-08 09:23 UTC, merged